БЛР2 Бахилин Никита
bakhilin/userspace_page_cache pull request #12
Opened 2024-12-13 07:00 UTC by bakhilin

2024-12-13 14:04 UTC, vityaman requested changes

2024-12-13 14:04 UTC, vityaman commented on src/cache.c
> +    }
Кажется, тут можно использовать цикл `for (size_t i = 0; ; i = (i + 1) % CACHE_SIZE;)`.

2024-12-13 14:04 UTC, vityaman commented on src/cache.c
> +        if (cache[i].valid)
Тут лучше прочитать указатель рассматриваемой странички в переменную, чтобы не писать везде `cache[i]` (error-prone).

2024-12-13 14:04 UTC, vityaman commented on src/cache.c
> +                cache[i].valid = 0;
Это можно вынести в отдельную процедуру и переиспользовать.

2024-12-13 14:04 UTC, vityaman commented on src/cache.c
> +                cache[i].valid = 0;
Давайте использовать `stdbool.h`.

2024-12-13 14:04 UTC, vityaman commented on src/cache.c
> +            return &cache[i];
Коды возврата! Аррррр

2024-12-13 14:04 UTC, vityaman commented on src/cache.c
> +            cache[i].data = malloc(BLOCK_SIZE);
Внезапно, `malloc` может вернуть `NULL`.

2024-12-13 14:04 UTC, vityaman commented on src/cache.c
> +            read(fd, cache[i].data, BLOCK_SIZE);
Вот это похоже на какой-то код инициализации страницы или, может быть, две разных процедуры инициализации: одна аллоцирует нас страничку, другая заполняет ее данными. Давайте вынесем в отдельные процедуры.

2024-12-13 14:04 UTC, vityaman commented on src/cache.c
> +        if (!cache[i].valid)
А вот этот цикл тоже хороший кандидат на процедуру а-ля `find_not_valid_page`.

2024-12-13 14:04 UTC, vityaman commented on src/cache.c
> +        perror("Failed to open file!");
Предлагаю не печатать сообщение об ошибке, а дать пользователю решить. Вдруг, он не хочет, чтобы что-то печаталось в консоль?

2024-12-13 14:04 UTC, vityaman commented on src/cache.c
> +            cache[i].valid = 0;
Кандидат на вынесение в отдельную процедуру.

2024-12-13 14:04 UTC, vityaman commented on src/cache.c
> +    }
Это не ошибка, мы должны уметь и с таким работать, системный `read` же умеет.

2024-12-13 14:04 UTC, vityaman commented on src/cache.c
> +    }
Это можно переписать

```c
if (!entry) {
  entry = load_into_cache_mem(fd, offset);
}
memcpy(buf, entry->data, count);
entry->referenced = 1; // maybe add some if to prevent referencing for the first time
return count;
```

2024-12-13 14:04 UTC, vityaman commented on src/cache.c
> +    }
Тоже можно переписать.

2024-12-13 14:04 UTC, vityaman commented on src/cache.c
> +    }
Это не ошибка.

2024-12-13 14:04 UTC, vityaman commented on src/cache.c
> +            cache[i].valid = 0;
Повторение кода.

2024-12-13 14:04 UTC, vityaman commented on src/main.c
> +    CU_add_test(suite, "Test WRITE to user cache", test_write_to_cache);
Вот за тесты уважение! Красавчик

2024-12-13 14:04 UTC, vityaman commented on include/cache.h
> +    int  valid;
Давай использовать `stdbool.h`.

2024-12-13 14:04 UTC, vityaman commented on include/cache.h
> +    int  fd;
Точно ли `fd` -- хороший ключ кэширования? А вдруг, мы откроем один файл несколько раз на чтение? Тогда мы не сможем переиспользовать его страницы, а будем хранить их в нескольких копиях.

2024-12-13 14:04 UTC, vityaman commented on src/cache.c
> +        if (cache[i].valid && cache[i].fd == fd && cache[i].offset == offset)
Стоямба. А вдруг offset будет какой-то не кратный `PAGE_SIZE`? Тогда мы страничку не найдем. Нужно весь файл логически поделить на блоки `PAGE_SIZE` и для интервала `offset` и `count` понимать, какие блоки его покрывают.

2024-12-13 16:44 UTC, bakhilin commented on src/cache.c
> +    }
fixed

2024-12-13 16:48 UTC, bakhilin commented on src/cache.c
> +        if (cache[i].valid)
fixed

2024-12-13 17:06 UTC, bakhilin commented on src/cache.c
> +                cache[i].valid = 0;
fixed

2024-12-13 17:08 UTC, bakhilin commented on src/cache.c
> +                cache[i].valid = 0;
fixed

2024-12-13 17:11 UTC, bakhilin commented on src/cache.c
> +            return &cache[i];
fixed

2024-12-13 17:11 UTC, bakhilin commented on src/cache.c
> +            cache[i].valid = 0;
fixed

2024-12-13 17:11 UTC, bakhilin commented on src/main.c
> +    CU_add_test(suite, "Test WRITE to user cache", test_write_to_cache);
fixed $)))$)$))$

2024-12-13 17:11 UTC, bakhilin commented on include/cache.h
> +    int  valid;
fixed

2024-12-13 18:17 UTC, vityaman commented on src/cache.c
> +            return &cache[i];
Мб тут, но не везде!

2024-12-13 18:20 UTC, bakhilin commented on src/cache.c
> +            return &cache[i];
хорошо, понял

2024-12-13 18:20 UTC, bakhilin commented on src/cache.c
> +        if (cache[i].valid && cache[i].fd == fd && cache[i].offset == offset)
посмотри пожалуйста сейчас @vityaman

2024-12-13 18:21 UTC, bakhilin commented on include/cache.h
> +    int  fd;
вроде бы fixed, заменил на inode

2024-12-16 16:45 UTC, bakhilin commented on src/cache.c
> +            cache[i].data = malloc(BLOCK_SIZE);
fixed

2024-12-17 07:46 UTC, bakhilin commented
@vityaman

2024-12-18 08:17 UTC, bakhilin commented
хочу доп @vityaman

2024-12-18 08:52 UTC, vityaman commented
Вечером посмотрю, а пока выдам такой доп. Давай сделаем так, чтобы наш кэш можно было использовать из нескольких потоков. Для этого можно использовать примитивы синхронизации из либс. Также давай напишем стресс-тест, который будет продолжительно случайным образом дергать ручки нашего кэша и проверять, что они возвращают корректный результат. Для этого имеет смысл реализовать какую-то чисто in-memory модель файловой системы, чтобы сравнивать результаты работы нашего кэша с моделью. Такой тест нужно будет прогнать под TSan.

2024-12-19 16:10 UTC, vityaman requested changes
Чето я вообще не понял этот код... Он работает?..

2024-12-19 16:10 UTC, vityaman commented on src/cache.c
> +}
Не пон. А где реализация?

2024-12-19 16:10 UTC, vityaman commented on src/cache.c
> +        exit(EXIT_FAILURE);
Я бы лучше пробросил ошибку кодом возврата пользователю.

2024-12-19 16:10 UTC, vityaman commented on src/cache.c
> +    if (read(fd,cache_page->data, BLOCK_SIZE) == -1) {
Какой уже пишу и говорю... Прочитайте man на read...

2024-12-19 16:10 UTC, vityaman commented on src/cache.c
> +    cache_write_t  * cache_page;
Эту переменную внутри стоит объявить, чтобы область видимости сузить.

2024-12-19 16:10 UTC, vityaman commented on src/cache.c
> +        scanf("%s", message_from_user);
???

2024-12-19 16:11 UTC, vityaman commented
Давай добавим запуск тестов в CI, без них не пойдет.

2024-12-19 16:35 UTC, bakhilin commented
Добавил CI @vityaman

2024-12-28 16:35 UTC, vityaman approved these changes

2025-01-22 12:55 UTC, closed without merging